// <auto-generated />
using System;
using InvalidOperation.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvalidOperation.Api.Migrations
{
    [DbContext(typeof(InvalidOperationApiContext))]
    partial class InvalidOperationApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvalidOperation.Api.Models.ActionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ActionRule");
                });

            modelBuilder.Entity("InvalidOperation.Api.Models.ActionRule", b =>
                {
                    b.OwnsOne("InvalidOperation.Api.Models.ActionRule+ActionRuleParameters", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("ActionRuleId")
                                .HasColumnType("uuid");

                            b1.HasKey("ActionRuleId");

                            b1.ToTable("ActionRule");

                            b1.ToJson("Parameters");

                            b1.WithOwner()
                                .HasForeignKey("ActionRuleId");

                            b1.OwnsMany("InvalidOperation.Api.Models.Action", "Actions", b2 =>
                                {
                                    b2.Property<Guid>("ActionRuleParametersActionRuleId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.HasKey("ActionRuleParametersActionRuleId", "Id");

                                    b2.ToTable("ActionRule");

                                    b2.WithOwner()
                                        .HasForeignKey("ActionRuleParametersActionRuleId");

                                    b2.OwnsOne("InvalidOperation.Api.Models.Action+EMail", "EMailParameter", b3 =>
                                        {
                                            b3.Property<Guid>("ActionRuleParametersActionRuleId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ActionId")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Message")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("ActionRuleParametersActionRuleId", "ActionId");

                                            b3.ToTable("ActionRule");

                                            b3.WithOwner()
                                                .HasForeignKey("ActionRuleParametersActionRuleId", "ActionId");
                                        });

                                    b2.OwnsOne("InvalidOperation.Api.Models.Action+Sms", "SMSParameter", b3 =>
                                        {
                                            b3.Property<Guid>("ActionRuleParametersActionRuleId")
                                                .HasColumnType("uuid");

                                            b3.Property<int>("ActionId")
                                                .HasColumnType("integer");

                                            b3.Property<string>("Message")
                                                .IsRequired()
                                                .HasColumnType("text");

                                            b3.HasKey("ActionRuleParametersActionRuleId", "ActionId");

                                            b3.ToTable("ActionRule");

                                            b3.WithOwner()
                                                .HasForeignKey("ActionRuleParametersActionRuleId", "ActionId");
                                        });

                                    b2.Navigation("EMailParameter")
                                        .IsRequired();

                                    b2.Navigation("SMSParameter")
                                        .IsRequired();
                                });

                            b1.Navigation("Actions");
                        });

                    b.Navigation("Parameters")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
